### PR TITLE
[RFC] switch fontawesome to git submodule

### PR DESCRIPTION
**Pull request by vapier**
Not sure how you feel about gitsubmodules, but it makes it easier to update.

### CODE REVIEW

**Comment by vapier** [comment]
if you'd rather not use gitsubmodules, i totally understand.  on a related note, the current fonts are outdated :).

**Comment by open-dynaMIX** [comment]
Sorry for the accidental close/reopen.

Thanks for the PR :tada:. I'm also not sure how I feel about submodules, never used them a lot :). But I guess it's the way to go.

Could you please also extend the README in regard to this change? And the checkout action might need a `submodules: 'true'`.

**Comment by open-dynaMIX** [comment]
@vapier I'd like to bring this PR into master. Are you gonna continue working on it, or should I finish it?

**Comment by vapier** [comment]
i prob won't get back to this anytime soon as i'm not currently using mpv :)

feel free to finish it up or just close

**Comment by open-dynaMIX** [comment]
Alright, thanks for letting me know!

**Pull request closed without merging**
