### PR TITLE
Slider easier to touch thumb and possible to touch on track on ios

### PR DESCRIPTION
**Pull request by rofrol**
More info  https://stackoverflow.com/questions/33343854/input-range-slider-not-working-on-ios-safari-when-clicking-on-track#comment103640266_33343854

Used https://github.com/sampotts/rangetouch

IMG_1661

### CODE REVIEW

**Comment by open-dynaMIX** [comment]
Hey @rofrol!

Thanks a lot for your contribution!

I have to say, I dislike the fact, that your proposed solution loads code from a cdn. Up until now simple-mpv-webui is fully self-contained and I would really like to keep it that way.

Do you think it would be possible to fix the issue in an other way?

I'm no frontend dev, but following quick and dirty hack seems to work in Safari on my old iPad:

```js
document.getElementById("mediaPosition").ontouchstart = function(e) {
  var slider = document.getElementById("mediaPosition");
  var percent = 100 / window.innerWidth * e.pageX;
  var sliderPos = slider.max / 100 * percent;
  send("set_position", sliderPos);
  setPosSlider(slider.max, sliderPos);
};
```

Of course it would have to be polished a bit and we'd have to make sure it doesn't interfere with browsers that already handle this nicely.

What do you think?

**Comment by rofrol** [comment]
Yes. We can extract relevant parts.

Also you calculate percentage using viewport width and not input width like here https://github.com/sampotts/rangetouch/blob/master/src/js/rangetouch.js#L146

Also I have tried your code and one nitpick is that when touching slider the track flashed for a moment.

What do you think about those bigger sliders and colors? I have no preference for colors, just that it is easy to touch and change.


slider_track_flashes

**Comment by open-dynaMIX** [comment]
> You calculate percentage using viewport width and not input width like here https://github.com/sampotts/rangetouch/blob/master/src/js/rangetouch.js#L146

You're right, we should absolutely use input width!

> What do you think about those bigger sliders and colors and margins? I have no preference for colors, just that it is easy to touch and change.

To be honest: I prefer the sliders as they are and I never had any problem using them (with chrome on android). However, since this is not the first time this is brought up, maybe I need to show some flexibility :)

There is another approach to this being discussed [here](#7).

> I have tried your code and one nitpick is that when touching slider the track flashed for a moment. I don't know yet why it's not like that when using rangetouch.js.

Yes, I saw that too. It would be great to be able to fix it, but honestly, I prefer some flashing on safari over loading external code.

**Comment by rofrol** [comment]
>There is another approach to this being discussed here.

wrong link `here`?

**Comment by rofrol** [comment]
you mean this approach: https://github.com/open-dynaMIX/simple-mpv-webui/pull/7 ?

I also thought about it.

Also about sending range vale all the time to the server, not on touch end.

**Comment by open-dynaMIX** [comment]
> wrong link here?

Sorry, it's fixed.

**Pull request closed without merging**
